### ISSUE TITLE
Curious lessons listing on 2022-03-19

### ISSUE THREAD

**Issue by toddfoster** [gbj/commonprayer#5]
Minor issue; please let me know if reports like this are uninteresting. I'm using (and appreciating) CommonPrayer regularly, and perhaps thereby noticing random edge cases (as well as learning about both the lectionary and your design choices!).

Concerning:
https://www.commonprayeronline.org/en/readings/office/2022-03-19

The office readings for most days will list the Psalms separately, but the readings as a list of three (first, second, Gospel) for a "full" office.

For saints' days, I notice CommonPrayer keeps them separate, since there are actually two sets of two readings and they often won't mesh together well (e.g., both morning and evening will draw from different sections of the same book to tell a story). 

This particular day, the Feast of St. Joseph, however, seems to do a little of both, grabbing the second reading from the evening and listing it as the first reading for BOTH morning and evening (thereby repeating it in the evening).

**Comment by toddfoster** [comment]
Also, no Sunday or Ash Wed. collect this day in Lent. Intentional?

**Comment by gbj** [comment]
Thanks!

a) 3/19 some of the readings seem to be marked inaccurately, so I'll fix that
b) I never have the Sunday collect for red-letter days, but this probably should have the Ash Wednesday/Lent seasonal collect, so thanks! (Feast days in Lent end up getting assigned a "Season" of "Saints" so they use the invitatory antiphons etc., for Saints, and a "Base Season" of "Lent" so they still don't include Alleluias etc., so the seasonal collects should probably check both)

These kind of bug reports are *extremely* helpful, especially because they're looking a few weeks in advance!

**Comment by gbj** [comment]
Fixed in db2e7f219ab782e912e8c739fbe46dd3fd48e210 and f6be488c7183b32265fb232fc8d398b81d90a706 and thanks again!
